import Head from "next/head";
import ButtonLogin from "@/components/shared/ButtonLogin";
import { TypewriterEffectSmooth } from "@/components/ui/typewriter-effect";
import { LampContainer } from "@/components/ui/lamp";
import { motion } from "framer-motion";

export default function Home() {
  const words = [
    {
      text: "Join",
      className: "text-white"
    },
    {
      text: "US",
      className: "text-white"
    },
    {
      text: "NOW.",
      className: "text-blue-500 dark:text-blue-500",
    },
  ];
  return (
    <div className={""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={""}>
        <LampContainer>
          <TypewriterEffectSmooth words={words} >
          </TypewriterEffectSmooth>
          <ButtonLogin />
        </LampContainer>
      </main>

      <footer className={""}></footer>
    </div>
  );
}
